name: CI Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node_version: ['14.x', '16.x', '18.x']

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Install dependences and run test
      run: |
        yarn
        yarn test
